- hosts: jenkins
  tasks:
  - name: install latest node source
    command: curl -sL https://rpm.nodesource.com/setup_14.x | sudo -E bash -
    become: yes
  - name: install Java & git
    yum:
      name:
      - java-1.8.0-openjdk-devel
      - git
      - nodejs
      - npm
      state: present

