- hosts: jenkins
  tasks:
  - name: install Java & git
    yum:
      name:
      - java-1.8.0-openjdk-devel
      - git
      state: present
  - name: add Jenkins repository
    yum_repository:
      name: jenkins
      state: present
      description: Official Jenkins Yum Repo
      baseurl: http://pkg.jenkins.io/redhat
      gpgkey: https://jenkins-ci.org/redhat/jenkins-ci.org.key
      gpgcheck: yes
      enabled: yes
  - name: Install Jenkins
      yum:
        name: jenkins
        update_cache: yes
        state: present
  - name: Enable and Start the Jenkins Service
    service:
      name: jenkins
      enabled: yes
      state: started