- hosts: jenkins
  tasks:
  - name: install latest node source
    shell: curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
  - name: install java, git, node
    yum:
      name:
      - java-1.8.0-openjdk-devel
      - git
      - nodejs
      update_cache: yes
      state: present